---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multitenancy-role
rules:
- apiGroups:
  - specs.kalexmills.com
  resources:
  - tenantresources
  - tenants
  verbs:
  - get
  - list
  - update
  - watch
